-- Extensoes e tipos enumerados usados em todo o schema normalizado.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS citext;   -- e-mail case-insensitive

CREATE TYPE model_status AS ENUM ('APPROVED', 'REJECTED', 'UNDER_ANALYSIS');
CREATE TYPE panel_type AS ENUM ('MONOCRYSTALLINE', 'POLYCRYSTALLINE', 'THIN_FILM');
CREATE TYPE supplier_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DEACTIVATED');
CREATE TYPE translation_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED');

CREATE TYPE billing_status AS ENUM ('PENDING', 'PAID', 'CANCELED', 'REFUNDED');
CREATE TYPE company_status AS ENUM ('UNDER_ANALYSIS', 'APPROVED', 'REJECTED');
CREATE TYPE payment_method AS ENUM ('PIX', 'BOLETO', 'CREDIT_CARD', 'TRANSFER');
CREATE TYPE plan_cycle AS ENUM ('MONTHLY', 'QUARTERLY', 'YEARLY');
CREATE TYPE subscription_status AS ENUM ('PAID', 'IN_DEBT', 'SUSPENDED');

CREATE TYPE service_status AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELED');

CREATE TYPE day_week AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE technical_affiliation_type AS ENUM ('INDEPENDENT', 'AFFILIATED', 'PARTNER');

CREATE TYPE proposal_status AS ENUM ('AWAITING_SUPPLIER', 'AWAITING_REQUESTER', 'ACCEPTED', 'REJECTED', 'CANCELED');

CREATE TYPE photo_type AS ENUM ('PROFILE', 'BANNER');
CREATE TYPE location_type AS ENUM ('BUILDING', 'HOUSE', 'COMPLEX');

CREATE TYPE account_status AS ENUM ('ACTIVE', 'LOCKED', 'DISABLED');
CREATE TYPE one_time_token_type AS ENUM ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ACCOUNT_LINK');
CREATE TYPE totp_algorithm AS ENUM ('SHA1', 'SHA256', 'SHA512');
CREATE TYPE security_event_type AS ENUM (
    'USER_REGISTERED', 'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'LOGOUT',
    'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED',
    'FEDERATED_IDENTITY_LINKED', 'FEDERATED_IDENTITY_UNLINKED',
    'MFA_ENABLED', 'MFA_DISABLED', 'MFA_CHALLENGE_FAILED',
    'REFRESH_TOKEN_REUSED', 'SESSION_REVOKED'
);
